package:
    name: intake-esm 
    version: 'v2022.11.11'

build: 
    number: '0'
    script: python -m pip install
source:
    git_url: https://github.com/intake/intake-esm 

about:
    description: 'An intake plugin for parsing an Earth System Model (ESM) catalog and loading assets into xarray datasets.
    doc_url: https://intake-esm.readthedocs.io/en/stable/
    home: https://github.com/intake/intake-esm 
    license: 'Apache License, Version 2.0' 
    summary: 'Intake plugin' 
    author: 'Anderson Banihirwe'
